### ISSUE TITLE
Nginx + Cloudflare Purge play for Ansible

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#150]
I would like to be able to run a quick Ansible play that both purges the proxy cache in Nginx, and purges relevant URLs in Cloudflare.

Right now I do that manually when I want to make sure a new article or changes post quickly to end users (otherwise it can be anywhere from 10-30 minutes before changes on the site are reflected in the real world).

The playbook should:

  1. Empty the contents of `/var/cache/nginx`
  2. Restart `nginx`
  3. Use Cloudflare's API to purge a list of URLs including:
     - https://www.jeffgeerling.com
     - https://www.jeffgeerling.com/blog
     - https://www.jeffgeerling.com/blog.xml
     - [the blog post in question]

**Comment by geerlingguy** [comment]
Well this shouldn't be too hard, actually...

```yaml
---
- hosts: mm
  become: true
  gather_facts: false

  vars:
    # API token should be created with cache_purge permissions.
    cloudflare_purge_zone: [get from cloudflare dashboard]
    cloudflare_purge_token: [create an API token with cache_purge permissions]
    cloudflare_purge_body:
      files:
        - https://www.jeffgeerling.com
        - https://www.jeffgeerling.com/blog
        - https://www.jeffgeerling.com/blog.xml
        - [other files to be purged here]

  tasks:
    - name: Empty out the nginx cache dir.
      shell: rm -f /var/cache/nginx/*

    - name: Restart nginx.
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Purge CloudFlare caches
      uri:
        body: '{{ cloudflare_purge_body | to_json }}'
        url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_purge_zone }}/purge_cache"
        method: DELETE
        body_format: json
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ cloudflare_purge_token }}"
```
