### ISSUE TITLE
Agenda for May 12 Livestream

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#73]
See previous agenda: #63

  - [x] 2020 Drupal Developer Survey: [Results are in!](https://www.jeffgeerling.com/blog/2020/2020-drupal-local-development-survey-results)
  - [x] Drupal music video of the week: [Drupal in the mornin, Drupal in the evenin' - DrupalCamp Florida 2013](https://www.youtube.com/watch?v=c4yE0e-Ly74)
  - [x] Final preparations:
    - [x] Test #55 on a fresh migration
    - [x] Build test `d8.jeffgeerling.com` instance on existing server
    - [ ] Build cutover punchlist (#84)

Video link: https://www.youtube.com/watch?v=SxR4N9inlYA

**Comment by geerlingguy** [comment]
So had a bit of an outage after deploying the new `d8.jeffgeerling.com` site...

The first problem was I had forgotten to add `ssl_enabled: false` to the vhost configuration I use to determine whether or not HTTPS config is added to the server in Nginx:

```yaml
  - server_name_canonical: d8.jeffgeerling.com
    drupal_docroot: /home/geerlingguy/domains/drupal8
    ssl_enabled: false
```

So after I deployed that fix (so the broken SSL config that was trying to load a `dhparam.pem` file that existed but couldn't be loaded twice by Nginx for some reason, causing an error like: `nginx: [emerg] BIO_new_file("/path/to/dhparam.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/path/to/dhparam.pem','r')`), I started getting a different error:

```
nginx: [emerg] host not found in upstream "d8.jeffgeerling.com" in /etc/nginx/sites-enabled/d8.jeffgeerling.com.conf:46
```

To fix _that_, I added an alias to the local hosts file (`/etc/hosts`) since the DNS was not pointed at this server (I'm just using it for testing):

```
127.0.0.1 d8.jeffgeerling.com
```

Now I'm getting a 404 but all my other Nginx sites are working properly, so I'm over that hump :) — a 404 I can deal with!

**Comment by geerlingguy** [comment]
I added a task to make sure all the Nginx hosts are listed in the hosts file, in case DNS has issues:

```yaml
- name: Ensure all the vhost hosts are listed in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item.server_name_canonical }}$'
    line: "{{ ansible_default_ipv4.address }} {{ item.server_name_canonical }}"
    state: present
  with_items: "{{ mm_nginx_vhosts }}"
```

**Comment by geerlingguy** [comment]
The 404 is because in D8, my codebase has a `web` folder where the docroot exists, so I had to update the docroot setting:

```
drupal_docroot: /home/geerlingguy/domains/drupal8/web
```

And now I'm also realizing I have to do a `composer install` since the codebase doesn't include the composer dependencies :D

**Comment by geerlingguy** [comment]
So I've added:

```yaml
- name: Ensure Drupal 8 codebase is present and updated.
  git:
    repo: https://github.com/geerlingguy/jeffgeerling-com.git
    version: master
    dest: /home/geerlingguy/domains/drupal8
    accept_hostkey: true
  become: true
  become_user: geerlingguy
  register: drupal8_codebase

- name: Make sure all Drupal 8 composer dependencies are installed.
  composer:
    command: install
    working_dir: /home/geerlingguy/domains/drupal8
  when: drupal8_codebase is changed
```
