### ISSUE TITLE
Fix spacing between checkmark boxes and text on Search filter blocks

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#94]
See illustration:

<img width="343" alt="Screen Shot 2020-05-19 at 10 46 26 AM" src="https://user-images.githubusercontent.com/481677/82348092-0aaa7280-99be-11ea-927e-d21ce7f6593a.png">

**Comment by geerlingguy** [comment]
The following:

```css
.block-facets li.facet-item .facets-checkbox {
  margin-right: 5px;
}
```

should fix it.
